### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by RebelCodeBase** [tpickett66/ansible-vault-rb#10]
We are having a discussion at [ansible_spec](https://github.com/volanja/ansible_spec/pull/116) whether to require this gem. Is it still maintained?

**Comment by tpickett66** [comment]
Yes, I'm still here although I'll admit I've been asleep at the wheel the last little bit.

**Comment by RebelCodeBase** [comment]
Very good! So my [pull request](https://github.com/volanja/ansible_spec/pull/116) for the [ansible_spec](https://github.com/volanja/ansible_spec) project has been accepted.
